name: First Workflow
on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Greeting
              run: echo "Hello this is your first step"
            - name: Print GoodBye
              run: echo "Your job executed successfully"
                